apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: roshanjayathunga/bth-booking-hotel-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: PGUSER
              value: booking_user
            - name: PGPASSWORD
              value: POSTGRES_PASSWORD
            - name: PGDATABASE
              value: booking_db
            - name: PGHOST
              value: postgres
            - name: PGPORT
              value: "5432"
